version: '2'
services:
  notifications-server:
    build: ./notifications-server
    depends_on:
      - redis
    ports:
      - "8080:8080"
    volumes:
      - "./notifications-server:/usr/src/app"
      - "./notifications-server/node_modules:/usr/src/app/node_modules"
    environment:
      - PORT=8080
      - REDIS_URI=redis://redis
  db:
    image: postgres
    environment:
      - POSTGRES_DB=spectateDB
      - POSTGRES_PASSWORD=icecold
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=icecold
  redis:
    image: redis
    ports:
      - "6379"
